package com.example.voicechanger

import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.widget.Toast
import androidx.activity.ComponentActivity
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.animation.AnimatedVisibility
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.core.content.FileProvider
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import java.io.File

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MaterialTheme(
                colorScheme = darkColorScheme(
                    primary = Color(0xFF1DB954),
                    secondary = Color(0xFF25D366),
                    background = Color(0xFF121212),
                    surface = Color(0xFF1E1E1E),
                    onSurface = Color.White
                )
            ) {
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colorScheme.background
                ) {
                    VoiceChangerScreen()
                }
            }
        }
    }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun VoiceChangerScreen() {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()

    var selectedFileUri by remember { mutableStateOf<Uri?>(null) }
    var selectedFileName by remember { mutableStateOf<String?>(null) }

    var isProcessing by remember { mutableStateOf(false) }
    var progressPercent by remember { mutableStateOf(0f) }
    var etaSeconds by remember { mutableStateOf(30f) }
    var elapsedSeconds by remember { mutableStateOf(0f) }
    var statusMessage by remember { mutableStateOf("Ready to process") }
    var errorMessage by remember { mutableStateOf<String?>(null) }

    var convertedFile by remember { mutableStateOf<File?>(null) }

    val filePickerLauncher = rememberLauncherForActivityResult(
        contract = ActivityResultContracts.GetContent()
    ) { uri: Uri? ->
        if (uri != null) {
            selectedFileUri = uri
            selectedFileName = uri.lastPathSegment ?: "Selected Audio File"
            convertedFile = null
            errorMessage = null
            statusMessage = "File selected. Tap 'Process Audio in Cloud'."
        }
    }

    fun shareToWhatsApp(file: File) {
        try {
            val contentUri = FileProvider.getUriForFile(
                context,
                "com.example.voicechanger.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "audio/*"
                putExtra(Intent.EXTRA_STREAM, contentUri)
                putExtra(Intent.EXTRA_TEXT, "Transformed Voice Audio file generated by VoiceChanger Cloud Service.")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                setPackage("com.whatsapp")
            }

            try {
                context.startActivity(shareIntent)
            } catch (e: Exception) {
                // If WhatsApp is not installed or specific package fails, fallback to general share chooser
                val chooserIntent = Intent.createChooser(
                    Intent(Intent.ACTION_SEND).apply {
                        type = "audio/*"
                        putExtra(Intent.EXTRA_STREAM, contentUri)
                        putExtra(Intent.EXTRA_TEXT, "Transformed Voice Audio file.")
                        addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
                    },
                    "Share Audio File to WhatsApp / Other Apps"
                )
                context.startActivity(chooserIntent)
            }
        } catch (e: Exception) {
            Toast.makeText(context, "Error launching share: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
        }
    }

    fun startCloudProcessing() {
        val uri = selectedFileUri ?: return
        isProcessing = true
        progressPercent = 0f
        etaSeconds = 30f
        elapsedSeconds = 0f
        statusMessage = "Submitting file to GCP Cloud Run..."
        errorMessage = null
        convertedFile = null

        coroutineScope.launch {
            val submitResult = CloudApiClient.submitJob(context, uri)
            submitResult.onSuccess { jobId ->
                statusMessage = "Job created! Processing on Cloud..."
                var isCompleted = false

                while (!isCompleted && isProcessing) {
                    delay(1500)
                    val statusResult = CloudApiClient.pollJobStatus(jobId)
                    statusResult.onSuccess { resp ->
                        progressPercent = resp.progressPercent
                        etaSeconds = resp.etaSeconds
                        elapsedSeconds = resp.elapsedSeconds
                        statusMessage = resp.statusMsg

                        if (resp.status == "completed" || resp.progressPercent >= 100f) {
                            isCompleted = true
                            statusMessage = "Downloading converted MP3 file..."

                            val dlResult = CloudApiClient.downloadAndSaveResult(
                                context,
                                jobId,
                                selectedFileName ?: "audio.mp3"
                            )
                            dlResult.onSuccess { file ->
                                convertedFile = file
                                isProcessing = false
                                statusMessage = "Completed! Saved to Music/VoiceChanger/"
                                Toast.makeText(context, "Audio Processed Successfully!", Toast.LENGTH_SHORT).show()
                            }.onFailure { err ->
                                isProcessing = false
                                errorMessage = "Download failed: ${err.message}"
                            }
                        } else if (resp.status == "failed") {
                            isCompleted = true
                            isProcessing = false
                            errorMessage = "Cloud job failed: ${resp.statusMsg}"
                        }
                    }.onFailure { err ->
                        // Retry polling gracefully on intermittent network glitches
                    }
                }
            }.onFailure { err ->
                isProcessing = false
                errorMessage = "Failed to submit job: ${err.message}"
            }
        }
    }

    Scaffold(
        topBar = {
            TopAppBar(
                title = {
                    Text(
                        "VoiceChanger Cloud AI",
                        fontWeight = FontWeight.Bold,
                        color = Color.White
                    )
                },
                colors = TopAppBarDefaults.topAppBarColors(
                    containerColor = Color(0xFF1E1E1E)
                )
            )
        }
    ) { paddingValues ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(paddingValues)
                .padding(16.dp)
                .verticalScroll(rememberScrollState()),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.spacedBy(16.dp)
        ) {
            // Service Status Card
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
                shape = RoundedCornerShape(12.dp)
            ) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(16.dp),
                    verticalAlignment = Alignment.CenterVertically,
                    horizontalArrangement = Arrangement.SpaceBetween
                ) {
                    Column {
                        Text(
                            "GCP Cloud Run Engine",
                            fontSize = 16.sp,
                            fontWeight = FontWeight.Bold,
                            color = Color.White
                        )
                        Text(
                            "asia-south1 (Mumbai) • Model Pre-Warmed",
                            fontSize = 12.sp,
                            color = Color(0xFFA0A0A0)
                        )
                    }
                    Box(
                        modifier = Modifier
                            .clip(RoundedCornerShape(8.dp))
                            .background(Color(0xFF1DB954))
                            .padding(horizontal = 8.dp, vertical = 4.dp)
                    ) {
                        Text(
                            "ONLINE",
                            fontSize = 10.sp,
                            fontWeight = FontWeight.Bold,
                            color = Color.Black
                        )
                    }
                }
            }

            // File Selection Section
            Card(
                modifier = Modifier.fillMaxWidth(),
                colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
                shape = RoundedCornerShape(12.dp)
            ) {
                Column(
                    modifier = Modifier.padding(16.dp),
                    verticalArrangement = Arrangement.spacedBy(12.dp)
                ) {
                    Text(
                        "Select Audio Input",
                        fontSize = 16.sp,
                        fontWeight = FontWeight.Bold,
                        color = Color.White
                    )

                    Button(
                        onClick = { filePickerLauncher.launch("audio/*") },
                        enabled = !isProcessing,
                        modifier = Modifier.fillMaxWidth(),
                        colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF333333))
                    ) {
                        Text("📁 Choose Audio / Video File", color = Color.White)
                    }

                    if (selectedFileUri != null) {
                        Text(
                            "Selected: ${selectedFileName ?: "Audio file"}",
                            fontSize = 14.sp,
                            color = Color(0xFF1DB954),
                            fontWeight = FontWeight.Medium
                        )
                    }
                }
            }

            // Process Action Button
            Button(
                onClick = { startCloudProcessing() },
                enabled = selectedFileUri != null && !isProcessing,
                modifier = Modifier
                    .fillMaxWidth()
                    .height(54.dp),
                shape = RoundedCornerShape(12.dp),
                colors = ButtonDefaults.buttonColors(
                    containerColor = Color(0xFF1DB954),
                    disabledContainerColor = Color(0xFF2E4E38)
                )
            ) {
                Text(
                    if (isProcessing) "⚡ Processing on GCP Cloud..." else "⚡ Convert Voice via Cloud",
                    fontSize = 16.sp,
                    fontWeight = FontWeight.Bold,
                    color = Color.Black
                )
            }

            // Progress & Status Card
            AnimatedVisibility(visible = isProcessing || progressPercent > 0f) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFF1E1E1E)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(
                        modifier = Modifier.padding(16.dp),
                        verticalArrangement = Arrangement.spacedBy(12.dp)
                    ) {
                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween,
                            verticalAlignment = Alignment.CenterVertically
                        ) {
                            Text(
                                "Live Cloud Progress",
                                fontWeight = FontWeight.Bold,
                                color = Color.White
                            )
                            Text(
                                "${progressPercent.toInt()}%",
                                fontWeight = FontWeight.Bold,
                                fontSize = 18.sp,
                                color = Color(0xFF1DB954)
                            )
                        }

                        LinearProgressIndicator(
                            progress = { (progressPercent / 100f).coerceIn(0f, 1f) },
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(8.dp)
                                .clip(RoundedCornerShape(4.dp)),
                            color = Color(0xFF1DB954),
                            trackColor = Color(0xFF333333)
                        )

                        Text(
                            statusMessage,
                            fontSize = 13.sp,
                            color = Color(0xFFA0A0A0)
                        )

                        Row(
                            modifier = Modifier.fillMaxWidth(),
                            horizontalArrangement = Arrangement.SpaceBetween
                        ) {
                            Text(
                                "Elapsed: ${elapsedSeconds.toInt()}s",
                                fontSize = 12.sp,
                                color = Color.Gray
                            )
                            Text(
                                "ETA: ${etaSeconds.toInt()}s",
                                fontSize = 12.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color(0xFF1DB954)
                            )
                        }
                    }
                }
            }

            // Error Display
            if (errorMessage != null) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFF4A1515)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Text(
                        errorMessage!!,
                        color = Color(0xFFFF6B6B),
                        modifier = Modifier.padding(16.dp),
                        fontSize = 14.sp
                    )
                }
            }

            // Completed Result & WhatsApp Sharing Card
            if (convertedFile != null) {
                Card(
                    modifier = Modifier.fillMaxWidth(),
                    colors = CardDefaults.cardColors(containerColor = Color(0xFF14301B)),
                    shape = RoundedCornerShape(12.dp)
                ) {
                    Column(
                        modifier = Modifier.padding(16.dp),
                        verticalArrangement = Arrangement.spacedBy(12.dp),
                        horizontalAlignment = Alignment.CenterHorizontally
                    ) {
                        Text(
                            "🎉 Voice Conversion Complete!",
                            fontWeight = FontWeight.Bold,
                            fontSize = 16.sp,
                            color = Color.White
                        )

                        Text(
                            "Saved to Public Output Folder:\n${convertedFile!!.name}",
                            fontSize = 13.sp,
                            color = Color(0xFFA0DDA0),
                            textAlign = TextAlign.Center
                        )

                        Button(
                            onClick = { shareToWhatsApp(convertedFile!!) },
                            modifier = Modifier
                                .fillMaxWidth()
                                .height(50.dp),
                            shape = RoundedCornerShape(10.dp),
                            colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF25D366))
                        ) {
                            Text(
                                "💬 Share to WhatsApp Group",
                                fontSize = 16.sp,
                                fontWeight = FontWeight.Bold,
                                color = Color.Black
                            )
                        }
                    }
                }
            }
        }
    }
}
